server.port=8080

spring.application.name=banking-system

# default profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


# Security properties

security.jwt_secret_key=404E635263336A586E3272357538782F413F4428472B4B6250645367566B5970
security.jwt_expiration_time = 86400000